.PHONY: clean All

All:
	@echo "----------Building project:[ Section_20_Challenge_4 - Debug ]----------"
	@cd "Section_20_Challenge_4" && "$(MAKE)" -f  "Section_20_Challenge_4.mk"
clean:
	@echo "----------Cleaning project:[ Section_20_Challenge_4 - Debug ]----------"
	@cd "Section_20_Challenge_4" && "$(MAKE)" -f  "Section_20_Challenge_4.mk" clean
