.PHONY: clean All

All:
	@echo "----------Building project:[ Section_20_Challenge_3 - Debug ]----------"
	@cd "Section_20_Challenge_3" && "$(MAKE)" -f  "Section_20_Challenge_3.mk"
clean:
	@echo "----------Cleaning project:[ Section_20_Challenge_3 - Debug ]----------"
	@cd "Section_20_Challenge_3" && "$(MAKE)" -f  "Section_20_Challenge_3.mk" clean
