.PHONY: clean All

All:
	@echo "----------Building project:[ Section_10_Challenge_Assignent - Debug ]----------"
	@cd "Section_10_Challenge_Assignent" && "$(MAKE)" -f  "Section_10_Challenge_Assignent.mk"
clean:
	@echo "----------Cleaning project:[ Section_10_Challenge_Assignent - Debug ]----------"
	@cd "Section_10_Challenge_Assignent" && "$(MAKE)" -f  "Section_10_Challenge_Assignent.mk" clean
